### ISSUE TITLE
No resizing of screen when changing window size and “fit to window” option is given in an RDP session

### ISSUE THREAD

**Issue by ilpssun** [maxsnts/XwRemote#10]
When I connect to an RDP server with the option size = “fit to window”, the remote display is set to the current size of the XwRemote window, which is as expected.  However, when I later change the windows size locally (of the XwRemote window), the remote display size is not adjusted.

I would expect the remote size to follow the local window size.  This should be either automatically (everytime I change the local window size) or possible to request manually by pressing a button or so.

**Comment by maxsnts** [comment]
Hum, is that possible? Resizing the remote session without disconnecting and connecting again?

I think  if we try on Msft RDP, it will just add scroll bars.

But i will check if i missed something and if possible i will implement it.

**Comment by ilpssun** [comment]
That might be true.  mRemoteNG seems to solve this by reconnecting to the server.  I'm not sure how the Microsoft RDP client handles that.  It does not seem to be reconnecting (at least not visibly).

**Comment by maxsnts** [comment]
What i see on my Microsoft RDP is that it does not change the remote resolution, instead i get scrollbars.

**Comment by ilpssun** [comment]
You are right, that is true for mstsc.exe.  However, the Windows app “[Microsoft Remote Desktop](https://www.microsoft.com/en-us/p/microsoft-remotedesktop/9wzdncrfj3ps?activetab=pivot:overviewtab)” (from the app store) seems to handle that smoothly.  If it's too hard to achieve, never mind.  It's not all that important 😃

**Comment by maxsnts** [comment]
Try v3.1.3.2 and see if it works for you.
It has to reconnect since it uses mstsc.
There is a new setting in the size combo setting.

**Comment by ilpssun** [comment]
Thanks for the lightning-fast fix 😃  The solution in v3.1.3.2 works for me.
