### ISSUE TITLE
Request XwRemote GUI multilingual support

### ISSUE THREAD

**Issue by wcxu21** [maxsnts/XwRemote#13]
Hi, I am from China. Could you consider adding multilingual support to the XwRemote GUI? Multiple languages allow more users to use your app.
I can help you translate Chinese language for free.
Thanks for your work.
：-）

**Comment by maxsnts** [comment]
Hi. 
That was not in the plans, but i will take a look and see how much work would that be.
To be honest, i am Portuguese but use all software in English, that is why i did not plan for multi language.
I have made multi-language apps before but hated it, but i will take a look.

**Comment by wcxu21** [comment]
thank you for your reply.
Adding multiple languages would allow more users to use the app, after all not everyone speaks English.
I provide free Chinese translations for many developers, and I also help them promote their apps in China.
I hope you can consider adding multiple languages, thank you for your work.
：-）

**Comment by maxsnts** [comment]
I thank you for the offer to translate XwRemote but sadly i will not be providing multi-language support at this time. 
Sorry.

I have been thinking about it and the reasons are as follows:

- XwRemote is a tech application and most tech people know at least some English.
- Translating into one extra language is opening a can of worms, then it would make sense to translate to other languages too.
- And last, to be completely honest, is a something that i done on other applications (professionally) and hated it.

In any case, if you require a multi-ptrotocol tool with multi-language, i recommend mRemoteNG.

Thank You
Best regards

**Comment by wcxu21** [comment]
thank you for your reply.
Hopefully in the future there will be an opportunity to add multilingual support.
thank you. ：-）
