### ISSUE TITLE
[request] fullscreen mode for display

### ISSUE THREAD

**Issue by olliem5** [maxsnts/XwRemote#14]
Started using XwRemote for remote desktop today, and was wondering if there were plans to add a fullscreen mode.
Currently, I am filling the screen to the window, but there is still some interface that I would like to hide.

**Comment by maxsnts** [comment]
When you say fullscreen, you mean the complete screen with not even the windows taskbar showing or some mode where XwRemote hides its interface but does not go full screen hiding the windows taskbar?

**Comment by olliem5** [comment]
Fullscreen with the XwInterface and Windows taskbar both hidden was what I was after.

**Comment by maxsnts** [comment]
Well, there is a new release with that support.
Try it out. I can not grantee perfection since the Microsoft RDP control is not the best thing to work with.
When changing from one mode to the other, it need to reconnect.
If you choose to start it in fullscreen, use the settings.

**Comment by olliem5** [comment]
Thank you very much for adding this, it is exactly what I was looking for!!
