### ISSUE TITLE
Close tab in global settings

### ISSUE THREAD

**Issue by sebasma78** [maxsnts/XwRemote#15]
On the "Global settings" dialog, when you click on the "Interface" tab you can see an "X" on the right.
If you click on it, the tab disappears.
Fortunately, it comes back if you reopen the dialog.
![Captura de pantalla 2022-03-29 174843](https://user-images.githubusercontent.com/45570361/160652661-5bbe4e20-b47c-4b83-be90-72ded5872051.png)

**Comment by maxsnts** [comment]
Hello.

I did not realize that there was a X button there.
Will remove soon.

Thank you

**Comment by maxsnts** [comment]
New build with a few minor corrections.
