### ISSUE TITLE
windows native ssh

### ISSUE THREAD

**Issue by plegrand1** [maxsnts/XwRemote#16]
Hello,
thanks for your application !
would it be possible to add the possibility to use the native version of ssh under windows (openssh) as well as the use of the .ssh folder to access the different keys?

thanks again

**Comment by maxsnts** [comment]
Honestly i don't think it is possible using putty as the terminal.
Putty requires key conversion.

Replacing Putty and using other terminal was something i tried already and failed miserably. 
Nothing comes close to putty on Windows (that i have found).

Sorry, i don't see a way of helping with this request.
