### ISSUE TITLE
Putty not found

### ISSUE THREAD

**Issue by hafedh-trimeche** [maxsnts/XwRemote#19]
Hello,

Please note that XwRemote wouldn't connect to SSH Server.
![XwRemote_3twiS4b3kS](https://user-images.githubusercontent.com/988584/197415532-5fceee7e-48f1-495f-9bbb-826ac5d4e4d0.png)

Regards.

**Comment by maxsnts** [comment]
Hi
Do you have putty.exe inside putty folder?
![image](https://user-images.githubusercontent.com/3869164/197417522-82f300bd-4d5d-4923-90ad-5d2d19115d3a.png)

**Comment by hafedh-trimeche** [comment]
Hi,

Indeed.
![explorer_gEKfUW2cqn](https://user-images.githubusercontent.com/988584/197417634-38fb74ab-53ba-4bc9-8b26-208575813509.png)

**Comment by maxsnts** [comment]
I would guess you are running XwRemote from a windows Shortcut.
Can you check the "working folder" of that shortcut?
Can you run XwRemote.exe directly and see if you get the same error?

**Comment by hafedh-trimeche** [comment]
Indeed, XwRemote was run from a windows Shortcut.

Running it from it's working directory was OK.

Adding the Working Directory to the Shortcut solved the problem.

It wold be better to expand the Application's (XwRemote) path (dynamically) with Putty Directory at Application's startup by using:
SetEnvironmentVariable API.

Best regards.

**Comment by maxsnts** [comment]
Most internal paths are calculated using the App folder, but i guess i missed that one.
I will check that.

Thank you

**Comment by maxsnts** [comment]
XwRemote was built under de assumption that the working folder would always be the exe folder.
I don't have the habit of creating shortcuts and defining the WorkingDirectory there.
So, in order to avid this in the future, the next version will reset the internal working folder to always be the exe folder.
