### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by stef97** [maxsnts/XwRemote#25]
Hi,
I apologize for asking such a "basic"  question but how do one install this on a Windows machine ?
Many thanks

**Comment by maxsnts** [comment]
There is no installation needed.
Just unzip the files from the latest version into any folder and run XwRemote.exe

![image](https://github.com/maxsnts/XwRemote/assets/3869164/6571304b-2924-4483-944b-ecf59fa97cbc)

**Comment by stef97** [comment]
Hi Max

The zip file from the GIThub does not have any exe file

[image: image.png]

**Comment by maxsnts** [comment]
The app zip has, from the realeases page -> https://github.com/maxsnts/XwRemote/releases/tag/v3.1.4.4
![image](https://github.com/maxsnts/XwRemote/assets/3869164/bbce69a2-9e88-48bb-93c0-d07dc98de49b)


The Source Code does not

**Comment by stef97** [comment]
Many thanks and ...appreciate your patience :-))

Steven

**Comment by maxsnts** [comment]
No problem
