### ISSUE TITLE
The internet has never heard of your software, save for this Github

### ISSUE THREAD

**Issue by allanonmage** [maxsnts/XwRemote#27]
I was hoping that there was a software that combined SSH, RDP, VNC, etc. together, and luckily enough, DDG recommended your software, albeit a few pages into the results.  Looks like you've been maintaining it for a while, too.

But aside from getting lucky that a search engine directed me here, the internet has otherwise never heard of your software, nor, it seems, anything like it.

I like to compare, contrast, and read/watch reviews about software before I install it and try it for myself, but I can't find anything** about your software online, which is very strange.

Are there any reviews of your software anywhere?  I've looked via DDG and YouTube.  I didn't make it through captcha hell to ask google.

**Surprisingly high given the otherwise lack of relevent results, and other info about your software.
**Besides the usual auto-generated garbage.

**Comment by maxsnts** [comment]
Hi.
Yeah, this is a niche tool. 
Mainly used by me and some coworkers.
I'm in the middle of a big rewrite, but the current version works fine.
I don't know about VNC though. 
That feature has bee added a few years ago but to be honest i never use it.
I will try update that part also in this rewrite.

As for honest reviews, i don't think you will find any.
This is a tool built by me mostly for me and i don't think many people use it.

As for you trying it, it need no install, its just an zip file, decompress it to a folder where you have write permissions (it needs to write the server information there), use the desktop.

Its has no malware or devious code, but again... a bad actor would also say that, so its up to you.
Usually o use Virtual Machines to test software.
