### ISSUE TITLE
Directory List Error

### ISSUE THREAD

**Issue by smaragdus** [maxsnts/XwRemote#8]
When I try to connect to a FTP server ([Storegate](https://www.storegate.com/en/) - **ftp1.storegate.com**) [XwRemote](https://github.com/maxsnts/XwRemote) connects successfully but it cannot retrieve the directory list:

```
An error occurred while retrieving the directory list.
Reason: ERROR: ListDirectory: /home => Timed out trying to read data from the socket stream!
```
**Screen:**

![XwRemote 3 1 1 1 - 2021-06-06 - error - 003](https://user-images.githubusercontent.com/9025757/120908010-220ed900-c66f-11eb-8070-6e01493b2d21.png)

However another client ([FTP Rush](https://www.wftpserver.com/ftprush_v2.htm), [version](https://www.wftpserver.com/clienthistory.htm) **2.2.0**) successfully retrieves the directory list:

**Screen:**

![FTP Rush 2 2 0 - 2021-06-06 - 002](https://user-images.githubusercontent.com/9025757/120908120-eaecf780-c66f-11eb-9742-d00600617518.png)

So it seems that the problem is not caused by the server but by the client ([XwRemote](https://github.com/maxsnts/XwRemote)).

Anyway, I find [XwRemote](https://github.com/maxsnts/XwRemote) to be a very useful program and if it is still in active development (I hope so) I may suggest some possible enhancements (mostly in the GUI department).

**Comment by maxsnts** [comment]
Hi

Can you please try with different "Connection Type" Settings?
![image](https://user-images.githubusercontent.com/3869164/120920682-e5b39b00-c6b7-11eb-8fca-be41c29d791a.png)

As for development, yes it is in development as time allows. 
I use it everyday (literally), all day at work, but i do changes only when i need them.
I'm the primary user, and honestly had no ideia other people were using it too.

Please make your suggestions. I will see what i can do about them.

Best regards

**Comment by smaragdus** [comment]
@maxsnts 

First, thanks for your quick response.

Now I tested all 3 Connection Type settings:

- Passive - Use routing info - Recommended
- Passive - Ignore routing info
- Active

While using the first two connection types(`Passive - Use routing info` and `Passive - Ignore routing info`) the client connects but it cannot retrieve the directory list. When using the third connection type (`Active`), it fails to connect (as I expected). When I opened this issue I had tested only the recommended connection type.

If you have time to investigate this problem further I may give you my credentials via e-mail so that you can test and try to find out what goes wrong with this particular FTP server. Just message me (smaragdus at zoho.com) and I will send you my user name and password for this FTP server (StoreGate).

By the ways I discovered [XwRemote](https://github.com/maxsnts/XwRemote) by chance, as far as I can remember I came upon it at [Softpedia](https://www.softpedia.com/get/Internet/Remote-Utils/XwRemote.shtml) and I was immediately impressed- it has a clean and handy GUI, it supports a good set of protocols and it seems natively portable (all data and settings are stored in `#XwRemoteServerDatabase#` file, right?) so although I rarely use it I appreciate your client very much (even though I have a natural aversion for #NET programs).

I may open some new issues with suggestions but of course I do not expect all of them or any of them to be implemented, I will just share with you my ideas for possible improvements of the program in future versions.

Best regards

**Comment by maxsnts** [comment]
OK, i will send you an email then. But if you can, create a read only user for this.
Thanks.

Yes the #XwRemoteServerDatabase# is the file with the settings.
_(Maybe if should have been #XwRemoteSettings#)_

Thank you

**Comment by maxsnts** [comment]
By the way, has you may have seen already, the FTP support is lacking many features.
My use of FTP is limited to upload and download a few files here and there as part of Server Administration, and the necessity for more features have not arouse yet.
I don't want to discourage you from suggesting changes, just saying that simplicity was kind of a feature.

**Comment by smaragdus** [comment]
@maxsnts 

Actually the problem with this particular server is not of great importance as I have several FTP clients which can retrieve the directory list without issues. It is just that I happened to encounter the problem mentioned above and felt obliged to report it. StoreGate is mostly cloud storage provider which allows connecting to it via FTP (which I use rarely to upload some files).

The directory structure of StoreGate looks like this:

`/home/smaragdus/Tox/Isotoxin/`

**screen:**

![StoreGate - 2021-06-07 - dir - 002](https://user-images.githubusercontent.com/9025757/120944732-c3189500-c73e-11eb-951d-f45c2b829685.png)

`Home - User - Sub-folder - Sub-folder`

Perhaps it is not worth the effort to investigate this any further.

**Comment by smaragdus** [comment]
I have just sent you an e-mail. I really don't want to waste your time. If it is hard to find out what prevents XwRemote from retrieving the directory list just leave it and I will close this issue.

Best regards

**Comment by maxsnts** [comment]
I think its OK in v3.1.2.0. 
Give it a try.

**Comment by smaragdus** [comment]
@maxsnts 

I have just tested [XwRemote](https://github.com/maxsnts/XwRemote) [version](https://github.com/maxsnts/XwRemote/releases) [3.1.2.0](https://github.com/maxsnts/XwRemote/releases/tag/v3.1.2.0) and I can confirm that now **XwRemote** successfully rerieves directory list, screen:

![XwRemote 3 1 2 0 - 2021-06-08 - 002](https://user-images.githubusercontent.com/9025757/121104194-30452c80-c80a-11eb-9d04-2abd8f683d2c.png)

Excellent work, thanks!

I am closing this issue.
