### ISSUE TITLE
System Tray Support

### ISSUE THREAD

**Issue by smaragdus** [maxsnts/XwRemote#9]
**Preamble**

I will appreciate if [XwRemote](https://github.com/maxsnts/XwRemote) offers options to be minimized/closed to system tray. Most of the FTP clients/download managers that I have used support minimizing/closing to system tray so I regard this a common feature.

**Suggestion**

Currently XwRemote has 3 tabs in Settings window:

- Security
- File Location
- SSH

You may add a new tab:

- General (or Interface)

with two check-boxes:

- Minimize to system tray (Minimize title bar button sends XwRemote to system tray)
- Close to system tray (Close title bar button sends XwRemote to system tray)

If this is implemented, XwRemote tray icon may have two context menu commands (on right click):

- Show
- Exit

Double click (which I prefer) or single click on system tray icon of XwRemote should maximize/restore XwRemote from system tray.

If only Minimize to system tray check-box is implemented I will be contented (although I prefer to minimize to task bar and to close to system tray).

**Usability**

Normally I open and use many programs so my task bar becomes cluttered and I prefer the programs which I don't need immediately to reside minimized in system tray so that I can restore them only when I need them. At least for me a native option to send XwRemote to system tray will be very handy. I said a native option because now I use an external tool- [SmartSystemMenu](https://github.com/AlexanderPro/SmartSystemMenu), which adds additional commands to title bar, to send XwRemote to system tray, screen:

![SmartSystemMenu 1 7 2 - 2021-06-07 - 001](https://user-images.githubusercontent.com/9025757/120942681-416f3a00-c733-11eb-80c4-182cb6341b00.png)

If you don't use system tray that much feel free to close this issue.

**Off-topic**

Looking at Settings window I noticed that there is no space in the title bar- **GlobalSettings** in stead of **Global Settings**, screen:

![XwRemote 3 1 1 1 - 2021-06-07 - 002](https://user-images.githubusercontent.com/9025757/120942840-1fc28280-c734-11eb-8552-5c6370d41c5d.png)

This is of no importance at all but I suppose that **Global Settings** will look better than **GlobalSettings**.

**Comment by maxsnts** [comment]
Sure, i will give the Tray Icon a try even though i have no use fot it.
XwRemote is my primary tool, its always front and center, but i see the ideia.

**Comment by maxsnts** [comment]
Included in v3.1.2.0. 
Give it a try.

**Comment by smaragdus** [comment]
@maxsnts 

Thank you very much for implementing system tray support in [XwRemote](https://github.com/maxsnts/XwRemote) [version](https://github.com/maxsnts/XwRemote/releases) [3.1.2.0](https://github.com/maxsnts/XwRemote/releases/tag/v3.1.2.0)!

However I think there is a tiny  glitch in the implementation of system tray support:

1. When only **Minimize to system tray** is selected, Minimize button sends **XwRemote** to task bar, screen:

![XwRemote 3 1 2 0 - 2021-06-08 - 006](https://user-images.githubusercontent.com/9025757/121105534-f6c1f080-c80c-11eb-8b5a-e7424e30e44b.png)

2. When only **Close to system tray** is selected, Minimize button sends **XwRemote** to system tray, screen:

![XwRemote 3 1 2 0 - 2021-06-08 - 004](https://user-images.githubusercontent.com/9025757/121105650-296be900-c80d-11eb-888d-de79f52c98b1.png)

3. When both **Minimize to system tray** and **Close to system tray** are selected, Minimize and Close buttons send **XwRemote** to system tray, screen:

![XwRemote 3 1 2 0 - 2021-06-08 - 008](https://user-images.githubusercontent.com/9025757/121105874-93848e00-c80d-11eb-98d7-1c6503b626f3.png)

I thinks that only **3** works as expected. I suppose that:

- When only **Minimize to system tray** is selected, Minimize button should send **XwRemote** to system tray only, not to task bar;
- When only **Close to system tray** is selected, Minimize button should send **XwRemote** to task bar;
- When both **Minimize to system tray** and **Close to system tray** are selected, Minimize and Close buttons send **XwRemote** to system tray, **XwRemote** works as expected;

Can you confirm this issue? Is it a bug or it is by design?

System ray commands:

- Show window
- Reset position
- Exit

work also fine. By the way what exactly **Reset position** command should do? I think it works exactly as **Show window** command. Am I missing something?

Thanks for changing **GlobalSettings** to **Global Settings**

Best regards.

**Comment by maxsnts** [comment]
Hi.
I think i got it corrected now. (Damn copy paste!)

Anywho, i have a weird setup, where my Windows is a Virtual Machine on a MAC in such a way that it actually "hides" windows from me, so there may be some behaviour that i missed.
Feel free to report it.

The "Reset position" is there because of my setup. During implementation i "lost" the window a couple times.
It show the window but reset its position to the middle of the screen.
I may remove that in the future if this tray icon feature does not misbehave.

Best Regards

**Comment by smaragdus** [comment]
@maxsnts 

I have just tested version [3.1.2.1](https://github.com/maxsnts/XwRemote/releases/tag/v3.1.2.1) with all possible combinations of system tray options and everything works as expected! Thank you very much!

**XwRemote** is a gem of a program and I am surprised that it is not very popular. However at [Softpedia](https://www.softpedia.com/get/Internet/Remote-Utils/XwRemote.shtml) editor's rating is **4.5/5** while users' rating is **4.8/5**. Actually I am just a causal user but for me **XwRemote** is handier to use than other similar programs I have used (both commercial and free). And the support is above excellent!

Many thanks for your help, for the fixes and for the implementation of tray support!

I am closing this issue as everything is working fine now.

Best regards
